//+------------------------------------------------------------------+
//|                                                      BaseEA.mq5  |
//|                         AI Trading Bot — Base Expert Advisor      |
//|                    Generated by AI Trading Bot (OpenRouter API)   |
//+------------------------------------------------------------------+
#property copyright   "AI Trading Bot"
#property link        "http://localhost:3000"
#property version     "1.00"
#property description "Base template for AI-generated Expert Advisors"
#property strict

#include <Trade\Trade.mqh>
#include <Trade\PositionInfo.mqh>
#include <Trade\OrderInfo.mqh>
#include <Indicators\Trend.mqh>

//+------------------------------------------------------------------+
//| Input Parameters                                                  |
//+------------------------------------------------------------------+

// ── General ─────────────────────────────────────────────
input group "=== General Settings ==="
input ulong   MagicNumber      = 123456;          // Magic Number
input string  EAComment        = "AI Trading Bot"; // Trade Comment
input bool    EnableTrading    = true;              // Enable Trading
input bool    EnableLogs       = true;              // Enable Detailed Logs

// ── Symbol & Timeframe ──────────────────────────────────
input group "=== Symbol & Timeframe ==="
input string  TradingSymbol    = "";               // Symbol (empty = current chart)
input ENUM_TIMEFRAMES TF       = PERIOD_CURRENT;  // Timeframe

// ── Risk Management ─────────────────────────────────────
input group "=== Risk Management ==="
input double  LotSize          = 0.01;            // Fixed Lot Size (0 = use risk %)
input double  RiskPercent      = 1.0;             // Risk % per trade (if LotSize=0)
input int     StopLossPips     = 50;              // Stop Loss (pips)
input int     TakeProfitPips   = 100;             // Take Profit (pips)
input bool    UseTrailingStop  = false;           // Enable Trailing Stop
input int     TrailingPips     = 20;              // Trailing Stop (pips)
input int     TrailingStep     = 5;               // Trailing Step (pips)
input int     BreakevenPips    = 30;              // Move SL to breakeven after (pips, 0=off)
input int     MaxOpenTrades    = 5;               // Max Open Trades
input double  MaxDailyLoss     = 5.0;             // Max Daily Loss % (0=off)

// ── Strategy Parameters ─────────────────────────────────
input group "=== Strategy Parameters ==="
input int     RSI_Period       = 14;              // RSI Period
input int     RSI_OverboughtLevel = 70;           // RSI Overbought Level
input int     RSI_OversoldLevel   = 30;           // RSI Oversold Level
input int     MA_FastPeriod    = 20;              // Fast MA Period
input int     MA_SlowPeriod    = 50;              // Slow MA Period
input ENUM_MA_METHOD MA_Method = MODE_EMA;        // MA Method
input int     MACD_Fast        = 12;              // MACD Fast Period
input int     MACD_Slow        = 26;              // MACD Slow Period
input int     MACD_Signal      = 9;               // MACD Signal Period
input int     BB_Period        = 20;              // Bollinger Bands Period
input double  BB_Deviation     = 2.0;             // Bollinger Bands Deviation

// ── Trading Sessions ────────────────────────────────────
input group "=== Trading Sessions ==="
input bool    UseSessions      = false;           // Filter by trading session
input int     SessionStartHour = 8;               // Session Start (server time hour)
input int     SessionEndHour   = 20;              // Session End (server time hour)
input bool    TradeMon = true;   // Trade Monday
input bool    TradeTue = true;   // Trade Tuesday
input bool    TradeWed = true;   // Trade Wednesday
input bool    TradeThu = true;   // Trade Thursday
input bool    TradeFri = true;   // Trade Friday

//+------------------------------------------------------------------+
//| Global Variables                                                  |
//+------------------------------------------------------------------+
CTrade        trade;
CPositionInfo posInfo;

string        symbol;
int           rsiHandle     = INVALID_HANDLE;
int           maFastHandle  = INVALID_HANDLE;
int           maSlowHandle  = INVALID_HANDLE;
int           macdHandle    = INVALID_HANDLE;
int           bbHandle      = INVALID_HANDLE;

double        dailyLossStart = 0;
datetime      lastBarTime    = 0;
datetime      tradingDayStart = 0;

//+------------------------------------------------------------------+
//| Expert initialization                                             |
//+------------------------------------------------------------------+
int OnInit()
{
   // Set symbol
   symbol = (TradingSymbol == "") ? _Symbol : TradingSymbol;

   // Configure trade object
   trade.SetExpertMagicNumber(MagicNumber);
   trade.SetDeviationInPoints(20);
   trade.SetTypeFilling(ORDER_FILLING_IOC);
   trade.LogLevel(LOG_LEVEL_ERRORS);

   // Initialize indicators
   rsiHandle    = iRSI(symbol, TF, RSI_Period, PRICE_CLOSE);
   maFastHandle = iMA(symbol, TF, MA_FastPeriod, 0, MA_Method, PRICE_CLOSE);
   maSlowHandle = iMA(symbol, TF, MA_SlowPeriod, 0, MA_Method, PRICE_CLOSE);
   macdHandle   = iMACD(symbol, TF, MACD_Fast, MACD_Slow, MACD_Signal, PRICE_CLOSE);
   bbHandle     = iBands(symbol, TF, BB_Period, 0, BB_Deviation, PRICE_CLOSE);

   // Validate handles
   if(rsiHandle == INVALID_HANDLE || maFastHandle == INVALID_HANDLE ||
      maSlowHandle == INVALID_HANDLE || macdHandle == INVALID_HANDLE ||
      bbHandle == INVALID_HANDLE)
   {
      Print("ERROR: Failed to create indicator handles");
      return INIT_FAILED;
   }

   // Validate symbol
   if(!SymbolSelect(symbol, true))
   {
      Print("ERROR: Cannot select symbol: ", symbol);
      return INIT_FAILED;
   }

   // Record daily start balance
   dailyLossStart = AccountInfoDouble(ACCOUNT_BALANCE);
   tradingDayStart = TimeCurrent();

   LogMsg("=== AI Trading Bot Initialized ===");
   LogMsg("Symbol: " + symbol + " | TF: " + EnumToString(TF));
   LogMsg("Magic: " + IntegerToString(MagicNumber));
   LogMsg("Lot: " + DoubleToString(LotSize, 2) + " | Risk: " + DoubleToString(RiskPercent, 1) + "%");
   LogMsg("SL: " + IntegerToString(StopLossPips) + " pips | TP: " + IntegerToString(TakeProfitPips) + " pips");

   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization                                           |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   // Release indicator handles
   if(rsiHandle    != INVALID_HANDLE) IndicatorRelease(rsiHandle);
   if(maFastHandle != INVALID_HANDLE) IndicatorRelease(maFastHandle);
   if(maSlowHandle != INVALID_HANDLE) IndicatorRelease(maSlowHandle);
   if(macdHandle   != INVALID_HANDLE) IndicatorRelease(macdHandle);
   if(bbHandle     != INVALID_HANDLE) IndicatorRelease(bbHandle);

   LogMsg("EA Deinitialized. Reason: " + IntegerToString(reason));
}

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
{
   if(!EnableTrading) return;

   // Process only on new bar
   datetime currentBar = iTime(symbol, TF, 0);
   if(currentBar == lastBarTime) {
      // Still manage trailing stop on every tick
      if(UseTrailingStop) ManageTrailingStop();
      return;
   }
   lastBarTime = currentBar;

   // Daily loss check
   if(!CheckDailyLoss()) return;

   // Session check
   if(UseSessions && !IsInSession()) return;

   // Day of week check
   if(!IsValidTradingDay()) return;

   // Get indicator values
   double rsi[], maFast[], maSlow[], macdMain[], macdSignal[], bbUpper[], bbMiddle[], bbLower[];
   ArraySetAsSeries(rsi, true);
   ArraySetAsSeries(maFast, true);
   ArraySetAsSeries(maSlow, true);
   ArraySetAsSeries(macdMain, true);
   ArraySetAsSeries(macdSignal, true);
   ArraySetAsSeries(bbUpper, true);
   ArraySetAsSeries(bbMiddle, true);
   ArraySetAsSeries(bbLower, true);

   if(CopyBuffer(rsiHandle,    0, 0, 3, rsi)       < 3) return;
   if(CopyBuffer(maFastHandle, 0, 0, 3, maFast)    < 3) return;
   if(CopyBuffer(maSlowHandle, 0, 0, 3, maSlow)    < 3) return;
   if(CopyBuffer(macdHandle,   0, 0, 3, macdMain)  < 3) return;
   if(CopyBuffer(macdHandle,   1, 0, 3, macdSignal)< 3) return;
   if(CopyBuffer(bbHandle,     1, 0, 3, bbUpper)   < 3) return;
   if(CopyBuffer(bbHandle,     0, 0, 3, bbMiddle)  < 3) return;
   if(CopyBuffer(bbHandle,     2, 0, 3, bbLower)   < 3) return;

   // Current price
   MqlTick tick;
   if(!SymbolInfoTick(symbol, tick)) return;

   // Check signals
   // ─── BUY Signal ──────────────────────────────────────────────────
   // Override this logic with your AI-generated strategy conditions
   bool buySignal  = CheckBuySignal(rsi, maFast, maSlow, macdMain, macdSignal, bbLower, bbMiddle, tick);
   bool sellSignal = CheckSellSignal(rsi, maFast, maSlow, macdMain, macdSignal, bbUpper, bbMiddle, tick);

   // Execute trades
   int openBuys  = CountPositions(POSITION_TYPE_BUY);
   int openSells = CountPositions(POSITION_TYPE_SELL);
   int totalOpen = openBuys + openSells;

   if(buySignal && totalOpen < MaxOpenTrades && openBuys == 0) {
      OpenBuy(tick.ask);
   }
   else if(sellSignal && totalOpen < MaxOpenTrades && openSells == 0) {
      OpenSell(tick.bid);
   }

   // Manage breakeven
   if(BreakevenPips > 0) ManageBreakeven();
}

//+------------------------------------------------------------------+
//| Buy/Sell Signal Logic — Customize this!                          |
//+------------------------------------------------------------------+
// Default: RSI oversold + MA cross up = BUY
bool CheckBuySignal(const double& rsi[], const double& maFast[], const double& maSlow[],
                    const double& macdMain[], const double& macdSignal[],
                    const double& bbLower[], const double& bbMiddle[], const MqlTick& tick)
{
   // RSI crossing up from oversold
   bool rsiOversold = rsi[1] < RSI_OversoldLevel && rsi[0] > RSI_OversoldLevel;

   // Fast MA above slow MA (uptrend)
   bool maTrend = maFast[0] > maSlow[0] && maFast[1] < maSlow[1];

   // MACD bullish cross
   bool macdCross = macdMain[1] < macdSignal[1] && macdMain[0] > macdSignal[0];

   return rsiOversold || (maTrend && macdMain[0] > 0);
}

// Default: RSI overbought + MA cross down = SELL
bool CheckSellSignal(const double& rsi[], const double& maFast[], const double& maSlow[],
                     const double& macdMain[], const double& macdSignal[],
                     const double& bbUpper[], const double& bbMiddle[], const MqlTick& tick)
{
   // RSI crossing down from overbought
   bool rsiOverbought = rsi[1] > RSI_OverboughtLevel && rsi[0] < RSI_OverboughtLevel;

   // Fast MA below slow MA (downtrend)
   bool maTrend = maFast[0] < maSlow[0] && maFast[1] > maSlow[1];

   // MACD bearish cross
   bool macdCross = macdMain[1] > macdSignal[1] && macdMain[0] < macdSignal[0];

   return rsiOverbought || (maTrend && macdMain[0] < 0);
}

//+------------------------------------------------------------------+
//| Open Buy/Sell positions                                           |
//+------------------------------------------------------------------+
bool OpenBuy(double price)
{
   double lot  = CalculateLotSize(StopLossPips);
   double point = SymbolInfoDouble(symbol, SYMBOL_POINT);
   int    digits = (int)SymbolInfoInteger(symbol, SYMBOL_DIGITS);
   double slMult = (digits == 3 || digits == 5) ? 10.0 : 1.0;

   double sl = (StopLossPips > 0) ? NormalizeDouble(price - StopLossPips * slMult * point, digits) : 0.0;
   double tp = (TakeProfitPips > 0) ? NormalizeDouble(price + TakeProfitPips * slMult * point, digits) : 0.0;

   bool result = trade.Buy(lot, symbol, price, sl, tp, EAComment);
   if(result) {
      LogMsg("BUY opened: " + DoubleToString(lot, 2) + " " + symbol +
             " @ " + DoubleToString(price, digits) +
             " | SL: " + DoubleToString(sl, digits) +
             " | TP: " + DoubleToString(tp, digits));
   } else {
      Print("BUY failed: ", trade.ResultRetcodeDescription());
   }
   return result;
}

bool OpenSell(double price)
{
   double lot  = CalculateLotSize(StopLossPips);
   double point = SymbolInfoDouble(symbol, SYMBOL_POINT);
   int    digits = (int)SymbolInfoInteger(symbol, SYMBOL_DIGITS);
   double slMult = (digits == 3 || digits == 5) ? 10.0 : 1.0;

   double sl = (StopLossPips > 0) ? NormalizeDouble(price + StopLossPips * slMult * point, digits) : 0.0;
   double tp = (TakeProfitPips > 0) ? NormalizeDouble(price - TakeProfitPips * slMult * point, digits) : 0.0;

   bool result = trade.Sell(lot, symbol, price, sl, tp, EAComment);
   if(result) {
      LogMsg("SELL opened: " + DoubleToString(lot, 2) + " " + symbol +
             " @ " + DoubleToString(price, digits) +
             " | SL: " + DoubleToString(sl, digits) +
             " | TP: " + DoubleToString(tp, digits));
   } else {
      Print("SELL failed: ", trade.ResultRetcodeDescription());
   }
   return result;
}

//+------------------------------------------------------------------+
//| Position Management                                               |
//+------------------------------------------------------------------+
void ManageTrailingStop()
{
   double point  = SymbolInfoDouble(symbol, SYMBOL_POINT);
   int    digits = (int)SymbolInfoInteger(symbol, SYMBOL_DIGITS);
   double slMult = (digits == 3 || digits == 5) ? 10.0 : 1.0;
   double trailDist = TrailingPips * slMult * point;
   double stepDist  = TrailingStep * slMult * point;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(!posInfo.SelectByIndex(i)) continue;
      if(posInfo.Magic() != MagicNumber) continue;
      if(posInfo.Symbol() != symbol) continue;

      if(posInfo.PositionType() == POSITION_TYPE_BUY)
      {
         double currentSL = posInfo.StopLoss();
         double bid = SymbolInfoDouble(symbol, SYMBOL_BID);
         double newSL = NormalizeDouble(bid - trailDist, digits);

         if(newSL > currentSL + stepDist)
         {
            trade.PositionModify(posInfo.Ticket(), newSL, posInfo.TakeProfit());
         }
      }
      else if(posInfo.PositionType() == POSITION_TYPE_SELL)
      {
         double currentSL = posInfo.StopLoss();
         double ask = SymbolInfoDouble(symbol, SYMBOL_ASK);
         double newSL = NormalizeDouble(ask + trailDist, digits);

         if(currentSL == 0.0 || newSL < currentSL - stepDist)
         {
            trade.PositionModify(posInfo.Ticket(), newSL, posInfo.TakeProfit());
         }
      }
   }
}

void ManageBreakeven()
{
   double point  = SymbolInfoDouble(symbol, SYMBOL_POINT);
   int    digits = (int)SymbolInfoInteger(symbol, SYMBOL_DIGITS);
   double slMult = (digits == 3 || digits == 5) ? 10.0 : 1.0;
   double beDist = BreakevenPips * slMult * point;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(!posInfo.SelectByIndex(i)) continue;
      if(posInfo.Magic() != MagicNumber) continue;
      if(posInfo.Symbol() != symbol) continue;

      double openPrice = posInfo.PriceOpen();

      if(posInfo.PositionType() == POSITION_TYPE_BUY)
      {
         double bid = SymbolInfoDouble(symbol, SYMBOL_BID);
         if(bid >= openPrice + beDist && posInfo.StopLoss() < openPrice)
            trade.PositionModify(posInfo.Ticket(), openPrice, posInfo.TakeProfit());
      }
      else if(posInfo.PositionType() == POSITION_TYPE_SELL)
      {
         double ask = SymbolInfoDouble(symbol, SYMBOL_ASK);
         if(ask <= openPrice - beDist && (posInfo.StopLoss() > openPrice || posInfo.StopLoss() == 0))
            trade.PositionModify(posInfo.Ticket(), openPrice, posInfo.TakeProfit());
      }
   }
}

//+------------------------------------------------------------------+
//| Utility Functions                                                 |
//+------------------------------------------------------------------+
int CountPositions(ENUM_POSITION_TYPE type)
{
   int count = 0;
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(posInfo.SelectByIndex(i) &&
         posInfo.Magic() == MagicNumber &&
         posInfo.Symbol() == symbol &&
         posInfo.PositionType() == type)
         count++;
   }
   return count;
}

double CalculateLotSize(int slPips)
{
   if(LotSize > 0) {
      return NormalizeLot(LotSize);
   }

   double balance  = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmt  = balance * RiskPercent / 100.0;
   double tickVal  = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_SIZE);
   double point    = SymbolInfoDouble(symbol, SYMBOL_POINT);
   int    digits   = (int)SymbolInfoInteger(symbol, SYMBOL_DIGITS);
   double slMult   = (digits == 3 || digits == 5) ? 10.0 : 1.0;

   if(slPips == 0 || tickVal == 0 || tickSize == 0) return NormalizeLot(0.01);

   double slPrice  = slPips * slMult * point;
   double lot      = riskAmt / (slPrice / tickSize * tickVal);

   return NormalizeLot(lot);
}

double NormalizeLot(double lot)
{
   double minLot  = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MIN);
   double maxLot  = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(symbol, SYMBOL_VOLUME_STEP);

   lot = MathFloor(lot / lotStep) * lotStep;
   lot = MathMax(minLot, MathMin(maxLot, lot));

   return NormalizeDouble(lot, 2);
}

bool CheckDailyLoss()
{
   if(MaxDailyLoss <= 0) return true;

   // Reset daily tracking at new day
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);
   MqlDateTime startDt;
   TimeToStruct(tradingDayStart, startDt);

   if(dt.day != startDt.day) {
      dailyLossStart = AccountInfoDouble(ACCOUNT_BALANCE);
      tradingDayStart = TimeCurrent();
   }

   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double loss = (dailyLossStart - balance) / dailyLossStart * 100.0;

   if(loss >= MaxDailyLoss) {
      LogMsg("Daily loss limit reached: " + DoubleToString(loss, 1) + "% (max " + DoubleToString(MaxDailyLoss, 1) + "%)");
      return false;
   }

   return true;
}

bool IsInSession()
{
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);
   return (dt.hour >= SessionStartHour && dt.hour < SessionEndHour);
}

bool IsValidTradingDay()
{
   MqlDateTime dt;
   TimeToStruct(TimeCurrent(), dt);

   switch(dt.day_of_week) {
      case 1: return TradeMon;
      case 2: return TradeTue;
      case 3: return TradeWed;
      case 4: return TradeThu;
      case 5: return TradeFri;
      default: return false;
   }
}

void LogMsg(string msg)
{
   if(EnableLogs)
      Print("[AI Bot] ", msg);
}
//+------------------------------------------------------------------+
